export default [
    {
        id: 1,
        solution: "nieve",
        desc: ""
    }, {
        id: 2,
        solution: "hueso",
        desc: ""
    }, {
        id: 3,
        solution: "titan",
        desc: ""
    }, {
        id: 4,
        solution: "flujo",
        desc: ""
    }, {
        id: 5,
        solution: "disco",
        desc: ""
    }, {
        id: 6,
        solution: "raz\xf3n",
        desc: ""
    }, {
        id: 7,
        solution: "mural",
        desc: ""
    }, {
        id: 8,
        solution: "abril",
        desc: ""
    }, {
        id: 9,
        solution: "vejez",
        desc: ""
    }, {
        id: 10,
        solution: "falso",
        desc: ""
    }, {
        id: 11,
        solution: "ca\xf1\xf3n",
        desc: ""
    }, {
        id: 12,
        solution: "obeso",
        desc: ""
    }, {
        id: 13,
        solution: "metal",
        desc: ""
    }, {
        id: 14,
        solution: "avena",
        desc: ""
    }, {
        id: 15,
        solution: "rubia",
        desc: ""
    }, {
        id: 16,
        solution: "pieza",
        desc: ""
    }, {
        id: 17,
        solution: "cuero",
        desc: ""
    }, {
        id: 18,
        solution: "noche",
        desc: ""
    }, {
        id: 19,
        solution: "bingo",
        desc: ""
    }, {
        id: 20,
        solution: "corto",
        desc: ""
    }, {
        id: 21,
        solution: "multa",
        desc: ""
    }, {
        id: 22,
        solution: "nieto",
        desc: ""
    }, {
        id: 23,
        solution: "dieta",
        desc: ""
    }, {
        id: 24,
        solution: "mosca",
        desc: ""
    }, {
        id: 25,
        solution: "nadal",
        desc: ""
    }, {
        id: 26,
        solution: "lider",
        desc: ""
    }, {
        id: 27,
        solution: "cerco",
        desc: ""
    }, {
        id: 28,
        solution: "rocio",
        desc: ""
    }, {
        id: 29,
        solution: "apoyo",
        desc: ""
    }, {
        id: 30,
        solution: "secta",
        desc: ""
    }, {
        id: 31,
        solution: "ganar",
        desc: ""
    }, {
        id: 32,
        solution: "besar",
        desc: ""
    }, {
        id: 33,
        solution: "novio",
        desc: ""
    }, {
        id: 34,
        solution: "albur",
        desc: ""
    }, {
        id: 35,
        solution: "litio",
        desc: ""
    }, {
        id: 36,
        solution: "llaga",
        desc: ""
    }, {
        id: 37,
        solution: "rueda",
        desc: ""
    }, {
        id: 38,
        solution: "corta",
        desc: ""
    }, {
        id: 39,
        solution: "feliz",
        desc: ""
    }, {
        id: 40,
        solution: "miope",
        desc: ""
    }, {
        id: 41,
        solution: "mojar",
        desc: ""
    }, {
        id: 42,
        solution: "cesta",
        desc: ""
    }, {
        id: 43,
        solution: "soplo",
        desc: ""
    }, {
        id: 44,
        solution: "nueve",
        desc: ""
    }, {
        id: 45,
        solution: "radio",
        desc: ""
    }, {
        id: 46,
        solution: "sexto",
        desc: ""
    }, {
        id: 47,
        solution: "sucio",
        desc: ""
    }, {
        id: 48,
        solution: "papel",
        desc: ""
    }, {
        id: 49,
        solution: "huevo",
        desc: ""
    }, {
        id: 50,
        solution: "polar",
        desc: ""
    }, {
        id: 51,
        solution: "rotar",
        desc: ""
    }, {
        id: 52,
        solution: "fuego",
        desc: ""
    }, {
        id: 53,
        solution: "lucir",
        desc: ""
    }, {
        id: 54,
        solution: "macho",
        desc: ""
    }, {
        id: 55,
        solution: "braza",
        desc: ""
    }, {
        id: 56,
        solution: "serio",
        desc: ""
    }, {
        id: 57,
        solution: "libra",
        desc: ""
    }, {
        id: 58,
        solution: "enano",
        desc: ""
    }, {
        id: 59,
        solution: "salsa",
        desc: ""
    }, {
        id: 60,
        solution: "ciego",
        desc: ""
    }, {
        id: 61,
        solution: "mujer",
        desc: ""
    }, {
        id: 62,
        solution: "sauna",
        desc: ""
    }, {
        id: 63,
        solution: "malta",
        desc: ""
    }, {
        id: 64,
        solution: "civil",
        desc: ""
    }, {
        id: 65,
        solution: "flota",
        desc: ""
    }, {
        id: 66,
        solution: "chile",
        desc: ""
    }, {
        id: 67,
        solution: "acudo",
        desc: ""
    }, {
        id: 68,
        solution: "modas",
        desc: ""
    }, {
        id: 69,
        solution: "criar",
        desc: ""
    }, {
        id: 70,
        solution: "hurto",
        desc: ""
    }, {
        id: 71,
        solution: "latir",
        desc: ""
    }, {
        id: 72,
        solution: "risas",
        desc: ""
    }, {
        id: 73,
        solution: "ganso",
        desc: ""
    }, {
        id: 74,
        solution: "suiza",
        desc: ""
    }, {
        id: 75,
        solution: "oto\xf1o",
        desc: ""
    }, {
        id: 76,
        solution: "suelo",
        desc: ""
    }, {
        id: 77,
        solution: "\xe9xito",
        desc: ""
    }, {
        id: 78,
        solution: "caber",
        desc: ""
    }, {
        id: 79,
        solution: "\xe9pica",
        desc: ""
    }, {
        id: 80,
        solution: "perra",
        desc: ""
    }, {
        id: 81,
        solution: "juego",
        desc: ""
    }, {
        id: 82,
        solution: "\xedgneo",
        desc: ""
    }, {
        id: 83,
        solution: "ingle",
        desc: ""
    }, {
        id: 84,
        solution: "mango",
        desc: ""
    }, {
        id: 85,
        solution: "ca\xedda",
        desc: ""
    }, {
        id: 86,
        solution: "doler",
        desc: ""
    }, {
        id: 87,
        solution: "\xe1lbum",
        desc: ""
    }, {
        id: 88,
        solution: "sudar",
        desc: ""
    }, {
        id: 89,
        solution: "duque",
        desc: ""
    }, {
        id: 90,
        solution: "curro",
        desc: ""
    }, {
        id: 91,
        solution: "musgo",
        desc: ""
    }, {
        id: 92,
        solution: "var\xf3n",
        desc: ""
    }, {
        id: 93,
        solution: "crear",
        desc: ""
    }, {
        id: 94,
        solution: "carne",
        desc: ""
    }, {
        id: 95,
        solution: "ovulo",
        desc: ""
    }, {
        id: 96,
        solution: "nivel",
        desc: ""
    }, {
        id: 97,
        solution: "villa",
        desc: ""
    }, {
        id: 98,
        solution: "moral",
        desc: ""
    }, {
        id: 99,
        solution: "parte",
        desc: ""
    }, {
        id: 100,
        solution: "anexo",
        desc: ""
    }, {
        id: 101,
        solution: "tapiz",
        desc: ""
    }, {
        id: 102,
        solution: "fecha",
        desc: ""
    }, {
        id: 103,
        solution: "sesgo",
        desc: ""
    }, {
        id: 104,
        solution: "ligar",
        desc: ""
    }, {
        id: 105,
        solution: "chino",
        desc: ""
    }, {
        id: 106,
        solution: "patio",
        desc: ""
    }, {
        id: 107,
        solution: "votar",
        desc: ""
    }, {
        id: 108,
        solution: "torso",
        desc: ""
    }, {
        id: 109,
        solution: "avi\xf3n",
        desc: ""
    }, {
        id: 110,
        solution: "dudar",
        desc: ""
    }, {
        id: 111,
        solution: "forja",
        desc: ""
    }, {
        id: 112,
        solution: "odiar",
        desc: ""
    }, {
        id: 113,
        solution: "\xfatero",
        desc: ""
    }, {
        id: 114,
        solution: "cauce",
        desc: ""
    }, {
        id: 115,
        solution: "hogar",
        desc: "Feliz d\xeda de la madre"
    }, {
        id: 116,
        solution: "relax",
        desc: ""
    }, {
        id: 117,
        solution: "yelmo",
        desc: ""
    }, {
        id: 118,
        solution: "regla",
        desc: ""
    }, {
        id: 119,
        solution: "marzo",
        desc: ""
    }, {
        id: 120,
        solution: "cairo",
        desc: ""
    }, {
        id: 121,
        solution: "a\xe9reo",
        desc: ""
    }, {
        id: 122,
        solution: "negro",
        desc: ""
    }, {
        id: 123,
        solution: "modal",
        desc: ""
    }, {
        id: 124,
        solution: "caldo",
        desc: ""
    }, {
        id: 125,
        solution: "museo",
        desc: ""
    }, {
        id: 126,
        solution: "abrir",
        desc: ""
    }, {
        id: 127,
        solution: "l\xe1ser",
        desc: ""
    }, {
        id: 128,
        solution: "signo",
        desc: ""
    }, {
        id: 129,
        solution: "nariz",
        desc: ""
    }, {
        id: 130,
        solution: "peine",
        desc: ""
    }, {
        id: 131,
        solution: "turno",
        desc: ""
    }, {
        id: 132,
        solution: "coche",
        desc: ""
    }, {
        id: 133,
        solution: "pleno",
        desc: ""
    }, {
        id: 134,
        solution: "fibra",
        desc: ""
    }, {
        id: 135,
        solution: "faena",
        desc: ""
    }, {
        id: 136,
        solution: "sitio",
        desc: ""
    }, {
        id: 137,
        solution: "balsa",
        desc: ""
    }, {
        id: 138,
        solution: "\xe1mbar",
        desc: ""
    }, {
        id: 139,
        solution: "recta",
        desc: ""
    }, {
        id: 140,
        solution: "aquel",
        desc: ""
    }, {
        id: 141,
        solution: "impar",
        desc: ""
    }, {
        id: 142,
        solution: "tonto",
        desc: ""
    }, {
        id: 143,
        solution: "tirar",
        desc: ""
    }, {
        id: 144,
        solution: "caras",
        desc: "30 DE MAYO<br>D\xeda Mundial de la Esclerosis M\xfaltiple, la enfermedad de las mil caras<br>\uD83D\uDCF2 <a href='http://www.diamundialem.org/'>www.diamundialem.org</a><br><br>Algunas organizaciones nacionales e internacionales:<br>\uD83C\uDDEA\uD83C\uDDF8 <a href='http://www.esclerosismultiple.com/'>Asociaci\xf3n Esclerosis M\xfaltiple Espa\xf1a</a><br>\uD83C\uDDEA\uD83C\uDDF8 <a href='http://www.aedem.org/'>Asociaci\xf3n Espa\xf1ola de Esclerosis M\xfaltiple</a><br>\uD83D\uDCC5 <a href='https://worldmsday.org/'>World Ms Day</a><br>\uD83C\uDF0D <a href='https://www.msif.org/'>Multiple Sclerosis International Federation</a><br>\uD83C\uDDEA\uD83C\uDDFA <a href='https://emsp.org/'>European Multiple Sclerosis Platform</a><br>\uD83E\uDDE0 <a href='https://www.sen.es/'>Sociedad Espa\xf1ola de Neurolog\xeda</a><br>\uD83D\uDC89 <a href='https://sedene.com/'>Sociedad Espa\xf1ola de Enfermer\xeda Neurol\xf3gica</a><br><br><a href='https://twitter.com/danielfrg'>@danielfrg</a> <a href='https://twitter.com/esclerosiseme'>@esclerosiseme</a>"
    }, {
        id: 145,
        solution: "fluir",
        desc: ""
    }, {
        id: 146,
        solution: "jap\xf3n",
        desc: ""
    }, {
        id: 147,
        solution: "lugar",
        desc: ""
    }, {
        id: 148,
        solution: "coger",
        desc: ""
    }, {
        id: 149,
        solution: "traza",
        desc: ""
    }, {
        id: 150,
        solution: "tibio",
        desc: ""
    }, {
        id: 151,
        solution: "tenis",
        desc: ""
    }, {
        id: 152,
        solution: "monto",
        desc: ""
    }, {
        id: 153,
        solution: "curva",
        desc: ""
    }, {
        id: 154,
        solution: "oveja",
        desc: ""
    }, {
        id: 155,
        solution: "rumor",
        desc: ""
    }, {
        id: 156,
        solution: "sobra",
        desc: ""
    }, {
        id: 157,
        solution: "helio",
        desc: ""
    }, {
        id: 158,
        solution: "\xe1baco",
        desc: ""
    }, {
        id: 159,
        solution: "gallo",
        desc: ""
    }, {
        id: 160,
        solution: "trama",
        desc: ""
    }, {
        id: 161,
        solution: "moler",
        desc: ""
    }, {
        id: 162,
        solution: "barro",
        desc: ""
    }, {
        id: 163,
        solution: "bando",
        desc: ""
    }, {
        id: 164,
        solution: "lista",
        desc: ""
    }, {
        id: 165,
        solution: "terna",
        desc: ""
    }, {
        id: 166,
        solution: "claro",
        desc: ""
    }, {
        id: 167,
        solution: "burla",
        desc: ""
    }, {
        id: 168,
        solution: "salir",
        desc: ""
    }, {
        id: 169,
        solution: "magia",
        desc: ""
    }, {
        id: 170,
        solution: "boxeo",
        desc: "<a href='https://twitch.tv/ibai'>La velada del a\xf1o II</a><br>\uD83C\uDDEA\uD83C\uDDF8 17:30 - \uD83C\uDDE6\uD83C\uDDF7 12:30 - \uD83C\uDDF2\uD83C\uDDFD 10:30 - \uD83C\uDDE8\uD83C\uDDF4 10:30"
    }, {
        id: 171,
        solution: "combo",
        desc: ""
    }, {
        id: 172,
        solution: "arepa",
        desc: ""
    }, {
        id: 173,
        solution: "d\xf3lar",
        desc: ""
    }, {
        id: 174,
        solution: "rifar",
        desc: ""
    }, {
        id: 175,
        solution: "ideal",
        desc: ""
    }, {
        id: 176,
        solution: "cinco",
        desc: ""
    }, {
        id: 177,
        solution: "cenar",
        desc: ""
    }, {
        id: 178,
        solution: "selva",
        desc: ""
    }, {
        id: 179,
        solution: "ray\xf3n",
        desc: ""
    }, {
        id: 180,
        solution: "tigre",
        desc: ""
    }, {
        id: 181,
        solution: "\xf3pera",
        desc: ""
    }, {
        id: 182,
        solution: "clave",
        desc: ""
    }, {
        id: 183,
        solution: "arp\xf3n",
        desc: ""
    }, {
        id: 184,
        solution: "karma",
        desc: ""
    }, {
        id: 185,
        solution: "subir",
        desc: ""
    }, {
        id: 186,
        solution: "banda",
        desc: ""
    }, {
        id: 187,
        solution: "cavar",
        desc: ""
    }, {
        id: 188,
        solution: "tenaz",
        desc: ""
    }, {
        id: 189,
        solution: "prima",
        desc: ""
    }, {
        id: 190,
        solution: "cerda",
        desc: ""
    }, {
        id: 191,
        solution: "arder",
        desc: ""
    }, {
        id: 192,
        solution: "pa\xf1al",
        desc: ""
    }, {
        id: 193,
        solution: "mixta",
        desc: ""
    }, {
        id: 194,
        solution: "lim\xf3n",
        desc: ""
    }, {
        id: 195,
        solution: "buena",
        desc: ""
    }, {
        id: 196,
        solution: "esp\xeda",
        desc: ""
    }, {
        id: 197,
        solution: "horno",
        desc: ""
    }, {
        id: 198,
        solution: "aguda",
        desc: ""
    }, {
        id: 199,
        solution: "polea",
        desc: ""
    }, {
        id: 200,
        solution: "sif\xf3n",
        desc: ""
    }, {
        id: 201,
        solution: "\xe1tomo",
        desc: ""
    }, {
        id: 202,
        solution: "cisne",
        desc: ""
    }, {
        id: 203,
        solution: "sufro",
        desc: ""
    }, {
        id: 204,
        solution: "sorda",
        desc: ""
    }, {
        id: 205,
        solution: "quedo",
        desc: ""
    }, {
        id: 206,
        solution: "te\xf1ir",
        desc: ""
    }, {
        id: 207,
        solution: "novia",
        desc: ""
    }, {
        id: 208,
        solution: "sordo",
        desc: ""
    }, {
        id: 209,
        solution: "tes\xf3n",
        desc: ""
    }, {
        id: 210,
        solution: "curso",
        desc: ""
    }, {
        id: 211,
        solution: "suena",
        desc: ""
    }, {
        id: 212,
        solution: "queso",
        desc: ""
    }, {
        id: 213,
        solution: "frase",
        desc: ""
    }, {
        id: 214,
        solution: "flaco",
        desc: ""
    }, {
        id: 215,
        solution: "rubio",
        desc: ""
    }, {
        id: 216,
        solution: "drama",
        desc: ""
    }, {
        id: 217,
        solution: "traje",
        desc: ""
    }, {
        id: 218,
        solution: "calvo",
        desc: ""
    }, {
        id: 219,
        solution: "suero",
        desc: ""
    }, {
        id: 220,
        solution: "ebrio",
        desc: ""
    }, {
        id: 221,
        solution: "\xe1rbol",
        desc: ""
    }, {
        id: 222,
        solution: "gasto",
        desc: ""
    }, {
        id: 223,
        solution: "golfo",
        desc: ""
    }, {
        id: 224,
        solution: "cacho",
        desc: ""
    }, {
        id: 225,
        solution: "primo",
        desc: ""
    }, {
        id: 226,
        solution: "rombo",
        desc: ""
    }, {
        id: 227,
        solution: "falsa",
        desc: ""
    }, {
        id: 228,
        solution: "diosa",
        desc: ""
    }, {
        id: 229,
        solution: "flaca",
        desc: ""
    }, {
        id: 230,
        solution: "bah\xeda",
        desc: ""
    }, {
        id: 231,
        solution: "dupla",
        desc: ""
    }, {
        id: 232,
        solution: "minar",
        desc: ""
    }, {
        id: 233,
        solution: "ilesa",
        desc: ""
    }, {
        id: 234,
        solution: "\xfanica",
        desc: ""
    }, {
        id: 235,
        solution: "viaje",
        desc: ""
    }, {
        id: 236,
        solution: "anual",
        desc: ""
    }, {
        id: 237,
        solution: "gansa",
        desc: ""
    }, {
        id: 238,
        solution: "muela",
        desc: ""
    }, {
        id: 239,
        solution: "zorro",
        desc: ""
    }, {
        id: 240,
        solution: "nuevo",
        desc: ""
    }, {
        id: 241,
        solution: "sutil",
        desc: ""
    }, {
        id: 242,
        solution: "dogma",
        desc: ""
    }, {
        id: 243,
        solution: "rimar",
        desc: ""
    }, {
        id: 244,
        solution: "mente",
        desc: ""
    }, {
        id: 245,
        solution: "libro",
        desc: ""
    }, {
        id: 246,
        solution: "chula",
        desc: ""
    }, {
        id: 247,
        solution: "rev\xe9s",
        desc: ""
    }, {
        id: 248,
        solution: "campo",
        desc: ""
    }, {
        id: 249,
        solution: "chico",
        desc: ""
    }, {
        id: 250,
        solution: "causa",
        desc: ""
    }, {
        id: 251,
        solution: "perro",
        desc: ""
    }, {
        id: 252,
        solution: "junto",
        desc: ""
    }, {
        id: 253,
        solution: "fauno",
        desc: ""
    }, {
        id: 254,
        solution: "digno",
        desc: ""
    }, {
        id: 255,
        solution: "tabla",
        desc: ""
    }, {
        id: 256,
        solution: "tocar",
        desc: ""
    }, {
        id: 257,
        solution: "culta",
        desc: ""
    }, {
        id: 258,
        solution: "piojo",
        desc: ""
    }, {
        id: 259,
        solution: "p\xedvot",
        desc: ""
    }, {
        id: 260,
        solution: "droga",
        desc: ""
    }, {
        id: 261,
        solution: "cifra",
        desc: ""
    }, {
        id: 262,
        solution: "monte",
        desc: ""
    }, {
        id: 263,
        solution: "zurda",
        desc: ""
    }, {
        id: 264,
        solution: "cromo",
        desc: ""
    }, {
        id: 265,
        solution: "kayak",
        desc: ""
    }, {
        id: 266,
        solution: "frita",
        desc: ""
    }, {
        id: 267,
        solution: "marea",
        desc: ""
    }, {
        id: 268,
        solution: "\xf3xido",
        desc: ""
    }, {
        id: 269,
        solution: "salmo",
        desc: ""
    }, {
        id: 270,
        solution: "fresa",
        desc: ""
    }, {
        id: 271,
        solution: "nadar",
        desc: ""
    }, {
        id: 272,
        solution: "presa",
        desc: ""
    }, {
        id: 273,
        solution: "bamb\xfa",
        desc: ""
    }, {
        id: 274,
        solution: "arena",
        desc: ""
    }, {
        id: 275,
        solution: "acoso",
        desc: ""
    }, {
        id: 276,
        solution: "b\xf3xer",
        desc: ""
    }, {
        id: 277,
        solution: "panda",
        desc: ""
    }, {
        id: 278,
        solution: "siega",
        desc: ""
    }, {
        id: 279,
        solution: "siete",
        desc: ""
    }, {
        id: 280,
        solution: "junio",
        desc: ""
    }, {
        id: 281,
        solution: "india",
        desc: ""
    }, {
        id: 282,
        solution: "marca",
        desc: ""
    }, {
        id: 283,
        solution: "abajo",
        desc: ""
    }, {
        id: 284,
        solution: "vac\xedo",
        desc: ""
    }, {
        id: 285,
        solution: "andes",
        desc: ""
    }, {
        id: 286,
        solution: "decir",
        desc: ""
    }, {
        id: 287,
        solution: "flama",
        desc: ""
    }, {
        id: 288,
        solution: "helar",
        desc: ""
    }, {
        id: 289,
        solution: "tarea",
        desc: ""
    }, {
        id: 290,
        solution: "danza",
        desc: ""
    }, {
        id: 291,
        solution: "poeta",
        desc: ""
    }, {
        id: 292,
        solution: "negra",
        desc: ""
    }, {
        id: 293,
        solution: "pacto",
        desc: ""
    }, {
        id: 294,
        solution: "pollo",
        desc: ""
    }, {
        id: 295,
        solution: "noble",
        desc: ""
    }, {
        id: 296,
        solution: "rat\xf3n",
        desc: ""
    }, {
        id: 297,
        solution: "bolsa",
        desc: ""
    }, {
        id: 298,
        solution: "lirio",
        desc: ""
    }, {
        id: 299,
        solution: "turco",
        desc: ""
    }, {
        id: 300,
        solution: "buz\xf3n",
        desc: ""
    }, {
        id: 301,
        solution: "fut\xf3n",
        desc: ""
    }, {
        id: 302,
        solution: "perla",
        desc: ""
    }, {
        id: 303,
        solution: "firme",
        desc: ""
    }, {
        id: 304,
        solution: "amado",
        desc: ""
    }, {
        id: 305,
        solution: "hinc\xf3",
        desc: ""
    }, {
        id: 306,
        solution: "plaza",
        desc: ""
    }, {
        id: 307,
        solution: "cabra",
        desc: ""
    }, {
        id: 308,
        solution: "regio",
        desc: ""
    }, {
        id: 309,
        solution: "cedro",
        desc: ""
    }, {
        id: 310,
        solution: "turba",
        desc: ""
    }, {
        id: 311,
        solution: "polio",
        desc: ""
    }, {
        id: 312,
        solution: "tropa",
        desc: ""
    }, {
        id: 313,
        solution: "luego",
        desc: ""
    }, {
        id: 314,
        solution: "cargo",
        desc: ""
    }, {
        id: 315,
        solution: "canal",
        desc: ""
    }, {
        id: 316,
        solution: "grama",
        desc: ""
    }, {
        id: 317,
        solution: "sabio",
        desc: ""
    }, {
        id: 318,
        solution: "viudo",
        desc: ""
    }, {
        id: 319,
        solution: "cocoa",
        desc: ""
    }, {
        id: 320,
        solution: "\xfanico",
        desc: ""
    }, {
        id: 321,
        solution: "jaula",
        desc: ""
    }, {
        id: 322,
        solution: "peral",
        desc: ""
    }, {
        id: 323,
        solution: "pulpa",
        desc: ""
    }, {
        id: 324,
        solution: "gripe",
        desc: ""
    }, {
        id: 325,
        solution: "cielo",
        desc: ""
    }, {
        id: 326,
        solution: "capta",
        desc: ""
    }, {
        id: 327,
        solution: "m\xf3vil",
        desc: ""
    }, {
        id: 328,
        solution: "icono",
        desc: ""
    }, {
        id: 329,
        solution: "canoa",
        desc: ""
    }, {
        id: 330,
        solution: "valle",
        desc: ""
    }, {
        id: 331,
        solution: "mixto",
        desc: ""
    }, {
        id: 332,
        solution: "t\xfanel",
        desc: ""
    }, {
        id: 333,
        solution: "marco",
        desc: ""
    }, {
        id: 334,
        solution: "ba\xf1ar",
        desc: ""
    }, {
        id: 335,
        solution: "vista",
        desc: ""
    }, {
        id: 336,
        solution: "troya",
        desc: ""
    }, {
        id: 337,
        solution: "hecho",
        desc: ""
    }, {
        id: 338,
        solution: "meter",
        desc: ""
    }, {
        id: 339,
        solution: "obvio",
        desc: ""
    }, {
        id: 340,
        solution: "palma",
        desc: ""
    }, {
        id: 341,
        solution: "guiar",
        desc: ""
    }, {
        id: 342,
        solution: "regia",
        desc: ""
    }, {
        id: 343,
        solution: "robot",
        desc: ""
    }, {
        id: 344,
        solution: "bar\xf3n",
        desc: ""
    }, {
        id: 345,
        solution: "brujo",
        desc: ""
    }, {
        id: 346,
        solution: "rotor",
        desc: ""
    }, {
        id: 347,
        solution: "messi",
        desc: ""
    }, {
        id: 348,
        solution: "punta",
        desc: ""
    }, {
        id: 349,
        solution: "pedir",
        desc: ""
    }, {
        id: 350,
        solution: "tarde",
        desc: ""
    }, {
        id: 351,
        solution: "nobel",
        desc: ""
    }, {
        id: 352,
        solution: "sidra",
        desc: ""
    }, {
        id: 353,
        solution: "pegar",
        desc: ""
    }, {
        id: 354,
        solution: "caoba",
        desc: ""
    }, {
        id: 355,
        solution: "reina",
        desc: ""
    }, {
        id: 356,
        solution: "seg\xfan",
        desc: ""
    }, {
        id: 357,
        solution: "sue\xf1o",
        desc: ""
    }, {
        id: 358,
        solution: "hielo",
        desc: ""
    }, {
        id: 359,
        solution: "feria",
        desc: ""
    }, {
        id: 360,
        solution: "mamba",
        desc: ""
    }, {
        id: 361,
        solution: "abeja",
        desc: ""
    }, {
        id: 362,
        solution: "carta",
        desc: ""
    }, {
        id: 363,
        solution: "baila",
        desc: ""
    }, {
        id: 364,
        solution: "pausa",
        desc: ""
    }, {
        id: 365,
        solution: "error",
        desc: ""
    }, {
        id: 366,
        solution: "rumbo",
        desc: ""
    }, {
        id: 367,
        solution: "culto",
        desc: ""
    }, {
        id: 368,
        solution: "panel",
        desc: ""
    }, {
        id: 369,
        solution: "leona",
        desc: ""
    }, {
        id: 370,
        solution: "pelar",
        desc: ""
    }, {
        id: 371,
        solution: "sucia",
        desc: ""
    }, {
        id: 372,
        solution: "polvo",
        desc: ""
    }, {
        id: 373,
        solution: "cruel",
        desc: ""
    }, {
        id: 374,
        solution: "amiga",
        desc: ""
    }, {
        id: 375,
        solution: "padre",
        desc: ""
    }, {
        id: 376,
        solution: "traga",
        desc: ""
    }, {
        id: 377,
        solution: "liana",
        desc: ""
    }, {
        id: 378,
        solution: "acera",
        desc: ""
    }, {
        id: 379,
        solution: "samba",
        desc: ""
    }, {
        id: 380,
        solution: "color",
        desc: ""
    }, {
        id: 381,
        solution: "fumar",
        desc: ""
    }, {
        id: 382,
        solution: "andar",
        desc: ""
    }, {
        id: 383,
        solution: "cacao",
        desc: ""
    }, {
        id: 384,
        solution: "norma",
        desc: ""
    }, {
        id: 385,
        solution: "sanar",
        desc: ""
    }, {
        id: 386,
        solution: "texto",
        desc: ""
    }, {
        id: 387,
        solution: "dicta",
        desc: ""
    }, {
        id: 388,
        solution: "dosis",
        desc: ""
    }, {
        id: 389,
        solution: "seria",
        desc: ""
    }, {
        id: 390,
        solution: "veloz",
        desc: ""
    }, {
        id: 391,
        solution: "toque",
        desc: ""
    }, {
        id: 392,
        solution: "l\xe1tex",
        desc: ""
    }, {
        id: 393,
        solution: "zurdo",
        desc: ""
    }, {
        id: 394,
        solution: "blusa",
        desc: ""
    }, {
        id: 395,
        solution: "arp\xeda",
        desc: ""
    }, {
        id: 396,
        solution: "cerca",
        desc: ""
    }, {
        id: 397,
        solution: "reino",
        desc: ""
    }, {
        id: 398,
        solution: "honor",
        desc: ""
    }, {
        id: 399,
        solution: "abono",
        desc: ""
    }, {
        id: 400,
        solution: "mando",
        desc: ""
    }, {
        id: 401,
        solution: "grasa",
        desc: ""
    }, {
        id: 402,
        solution: "so\xf1ar",
        desc: ""
    }, {
        id: 403,
        solution: "caida",
        desc: ""
    }, {
        id: 404,
        solution: "magro",
        desc: ""
    }, {
        id: 405,
        solution: "copia",
        desc: ""
    }, {
        id: 406,
        solution: "guion",
        desc: ""
    }, {
        id: 407,
        solution: "v\xeddeo",
        desc: ""
    }, {
        id: 408,
        solution: "cesto",
        desc: ""
    }, {
        id: 409,
        solution: "oxido",
        desc: ""
    }, {
        id: 410,
        solution: "m\xf3dem",
        desc: ""
    }, {
        id: 411,
        solution: "circo",
        desc: ""
    }, {
        id: 412,
        solution: "cegar",
        desc: ""
    }, {
        id: 413,
        solution: "coral",
        desc: ""
    }, {
        id: 414,
        solution: "erizo",
        desc: ""
    }, {
        id: 415,
        solution: "chica",
        desc: ""
    }, {
        id: 416,
        solution: "huida",
        desc: ""
    }, {
        id: 417,
        solution: "plano",
        desc: ""
    }, {
        id: 418,
        solution: "\xe1cido",
        desc: ""
    }, {
        id: 419,
        solution: "antro",
        desc: ""
    }, {
        id: 420,
        solution: "total",
        desc: ""
    }, {
        id: 421,
        solution: "bajar",
        desc: ""
    }, {
        id: 422,
        solution: "broma",
        desc: ""
    }, {
        id: 423,
        solution: "carga",
        desc: ""
    }, {
        id: 424,
        solution: "remar",
        desc: ""
    }, {
        id: 425,
        solution: "bella",
        desc: ""
    }, {
        id: 426,
        solution: "monje",
        desc: ""
    }, {
        id: 427,
        solution: "lenta",
        desc: ""
    }, {
        id: 428,
        solution: "rural",
        desc: ""
    }, {
        id: 429,
        solution: "arroz",
        desc: ""
    }, {
        id: 430,
        solution: "costa",
        desc: ""
    }, {
        id: 431,
        solution: "fruto",
        desc: ""
    }, {
        id: 432,
        solution: "cauto",
        desc: ""
    }, {
        id: 433,
        solution: "folio",
        desc: ""
    }, {
        id: 434,
        solution: "mansa",
        desc: ""
    }, {
        id: 435,
        solution: "roble",
        desc: ""
    }, {
        id: 436,
        solution: "oeste",
        desc: ""
    }, {
        id: 437,
        solution: "mundo",
        desc: ""
    }, {
        id: 438,
        solution: "pulpo",
        desc: ""
    }, {
        id: 439,
        solution: "caj\xf3n",
        desc: ""
    }, {
        id: 440,
        solution: "gnomo",
        desc: ""
    }, {
        id: 441,
        solution: "lucho",
        desc: ""
    }, {
        id: 442,
        solution: "armar",
        desc: ""
    }, {
        id: 443,
        solution: "bruja",
        desc: ""
    }, {
        id: 444,
        solution: "visto",
        desc: ""
    }, {
        id: 445,
        solution: "cazar",
        desc: ""
    }, {
        id: 446,
        solution: "ruina",
        desc: ""
    }, {
        id: 447,
        solution: "vello",
        desc: ""
    }, {
        id: 448,
        solution: "falla",
        desc: ""
    }, {
        id: 449,
        solution: "\xe1nimo",
        desc: ""
    }, {
        id: 450,
        solution: "bicho",
        desc: ""
    }, {
        id: 451,
        solution: "calma",
        desc: ""
    }, {
        id: 452,
        solution: "letra",
        desc: ""
    }, {
        id: 453,
        solution: "placa",
        desc: ""
    }, {
        id: 454,
        solution: "tecla",
        desc: ""
    }, {
        id: 455,
        solution: "acuso",
        desc: ""
    }, {
        id: 456,
        solution: "f\xe1cil",
        desc: ""
    }, {
        id: 457,
        solution: "misil",
        desc: ""
    }, {
        id: 458,
        solution: "forro",
        desc: ""
    }, {
        id: 459,
        solution: "rival",
        desc: ""
    }, {
        id: 460,
        solution: "sue\xf1a",
        desc: ""
    }, {
        id: 461,
        solution: "a\xe9rea",
        desc: ""
    }, {
        id: 462,
        solution: "furor",
        desc: ""
    }, {
        id: 463,
        solution: "duelo",
        desc: ""
    }, {
        id: 464,
        solution: "buf\xf3n",
        desc: ""
    }, {
        id: 465,
        solution: "sacar",
        desc: ""
    }, {
        id: 466,
        solution: "se\xf1or",
        desc: ""
    }, {
        id: 467,
        solution: "cari\xe9",
        desc: ""
    }, {
        id: 468,
        solution: "racha",
        desc: ""
    }, {
        id: 469,
        solution: "prisa",
        desc: ""
    }, {
        id: 470,
        solution: "due\xf1a",
        desc: ""
    }, {
        id: 471,
        solution: "clavo",
        desc: ""
    }, {
        id: 472,
        solution: "cerdo",
        desc: ""
    }, {
        id: 473,
        solution: "flora",
        desc: ""
    }, {
        id: 474,
        solution: "piano",
        desc: ""
    }, {
        id: 475,
        solution: "panal",
        desc: ""
    }, {
        id: 476,
        solution: "radar",
        desc: ""
    }, {
        id: 477,
        solution: "cueva",
        desc: ""
    }, {
        id: 478,
        solution: "pesca",
        desc: ""
    }, {
        id: 479,
        solution: "tumor",
        desc: ""
    }, {
        id: 480,
        solution: "plomo",
        desc: ""
    }, {
        id: 481,
        solution: "beber",
        desc: ""
    }, {
        id: 482,
        solution: "local",
        desc: ""
    }, {
        id: 483,
        solution: "guapo",
        desc: ""
    }, {
        id: 484,
        solution: "hebra",
        desc: ""
    }, {
        id: 485,
        solution: "yerba",
        desc: ""
    }, {
        id: 486,
        solution: "rapel",
        desc: ""
    }, {
        id: 487,
        solution: "silla",
        desc: ""
    }, {
        id: 488,
        solution: "himno",
        desc: ""
    }, {
        id: 489,
        solution: "monja",
        desc: ""
    }, {
        id: 490,
        solution: "clara",
        desc: ""
    }, {
        id: 491,
        solution: "api\xf1o",
        desc: ""
    }, {
        id: 492,
        solution: "recto",
        desc: ""
    }, {
        id: 493,
        solution: "burro",
        desc: ""
    }, {
        id: 494,
        solution: "volar",
        desc: ""
    }, {
        id: 495,
        solution: "acaso",
        desc: ""
    }, {
        id: 496,
        solution: "rusia",
        desc: ""
    }, {
        id: 497,
        solution: "valla",
        desc: ""
    }, {
        id: 498,
        solution: "cruce",
        desc: ""
    }, {
        id: 499,
        solution: "quien",
        desc: ""
    }, {
        id: 500,
        solution: "ansia",
        desc: ""
    }, {
        id: 501,
        solution: "oasis",
        desc: ""
    }, {
        id: 502,
        solution: "nadie",
        desc: ""
    }, {
        id: 503,
        solution: "fetal",
        desc: ""
    }, {
        id: 504,
        solution: "fre\xedr",
        desc: ""
    }, {
        id: 505,
        solution: "pesar",
        desc: ""
    }, {
        id: 506,
        solution: "se\xf1al",
        desc: ""
    }, {
        id: 507,
        solution: "magno",
        desc: ""
    }, {
        id: 508,
        solution: "firma",
        desc: ""
    }, {
        id: 509,
        solution: "colmo",
        desc: ""
    }, {
        id: 510,
        solution: "viral",
        desc: ""
    }, {
        id: 511,
        solution: "menta",
        desc: ""
    }, {
        id: 512,
        solution: "pizza",
        desc: ""
    }, {
        id: 513,
        solution: "tengo",
        desc: ""
    }, {
        id: 514,
        solution: "ileso",
        desc: ""
    }, {
        id: 515,
        solution: "gamba",
        desc: ""
    }, {
        id: 516,
        solution: "canon",
        desc: ""
    }, {
        id: 517,
        solution: "man\xeda",
        desc: ""
    }, {
        id: 518,
        solution: "cameo",
        desc: ""
    }, {
        id: 519,
        solution: "vivir",
        desc: ""
    }, {
        id: 520,
        solution: "furia",
        desc: ""
    }, {
        id: 521,
        solution: "rompe",
        desc: ""
    }, {
        id: 522,
        solution: "fallo",
        desc: ""
    }, {
        id: 523,
        solution: "oruga",
        desc: ""
    }, {
        id: 524,
        solution: "julio",
        desc: ""
    }, {
        id: 525,
        solution: "alzar",
        desc: ""
    }, {
        id: 526,
        solution: "altar",
        desc: ""
    }, {
        id: 527,
        solution: "llama",
        desc: ""
    }, {
        id: 528,
        solution: "calor",
        desc: ""
    }, {
        id: 529,
        solution: "cobra",
        desc: ""
    }, {
        id: 530,
        solution: "salvo",
        desc: ""
    }, {
        id: 531,
        solution: "l\xe1piz",
        desc: ""
    }, {
        id: 532,
        solution: "playa",
        desc: ""
    }, {
        id: 533,
        solution: "crema",
        desc: ""
    }, {
        id: 534,
        solution: "medir",
        desc: ""
    }, {
        id: 535,
        solution: "ducha",
        desc: ""
    }, {
        id: 536,
        solution: "acida",
        desc: ""
    }, {
        id: 537,
        solution: "fisco",
        desc: ""
    }, {
        id: 538,
        solution: "fl\xfaor",
        desc: ""
    }, {
        id: 539,
        solution: "palmo",
        desc: ""
    }, {
        id: 540,
        solution: "tango",
        desc: ""
    }, {
        id: 541,
        solution: "cobre",
        desc: ""
    }, {
        id: 542,
        solution: "ninja",
        desc: ""
    }, {
        id: 543,
        solution: "censo",
        desc: ""
    }, {
        id: 544,
        solution: "apodo",
        desc: ""
    }, {
        id: 545,
        solution: "esqu\xed",
        desc: ""
    }, {
        id: 546,
        solution: "hojea",
        desc: ""
    }, {
        id: 547,
        solution: "magra",
        desc: ""
    }, {
        id: 548,
        solution: "rompo",
        desc: ""
    }, {
        id: 549,
        solution: "agria",
        desc: ""
    }, {
        id: 550,
        solution: "chulo",
        desc: ""
    }, {
        id: 551,
        solution: "al\xeden",
        desc: ""
    }, {
        id: 552,
        solution: "bueno",
        desc: ""
    }, {
        id: 553,
        solution: "tejer",
        desc: ""
    }, {
        id: 554,
        solution: "vaci\xf3",
        desc: ""
    }, {
        id: 555,
        solution: "grano",
        desc: ""
    }, {
        id: 556,
        solution: "jugar",
        desc: ""
    }, {
        id: 557,
        solution: "deseo",
        desc: ""
    }, {
        id: 558,
        solution: "ostra",
        desc: ""
    }, {
        id: 559,
        solution: "apaga",
        desc: ""
    }, {
        id: 560,
        solution: "hotel",
        desc: ""
    }, {
        id: 561,
        solution: "tener",
        desc: ""
    }, {
        id: 562,
        solution: "ictus",
        desc: ""
    }, {
        id: 563,
        solution: "exijo",
        desc: ""
    }, {
        id: 564,
        solution: "toldo",
        desc: ""
    }, {
        id: 565,
        solution: "metro",
        desc: ""
    }, {
        id: 566,
        solution: "d\xf3nut",
        desc: ""
    }, {
        id: 567,
        solution: "atroz",
        desc: ""
    }, {
        id: 568,
        solution: "\xe1ngel",
        desc: ""
    }, {
        id: 569,
        solution: "hongo",
        desc: ""
    }, {
        id: 570,
        solution: "fot\xf3n",
        desc: ""
    }, {
        id: 571,
        solution: "golpe",
        desc: ""
    }, {
        id: 572,
        solution: "pu\xf1al",
        desc: ""
    }, {
        id: 573,
        solution: "ronda",
        desc: ""
    }, {
        id: 574,
        solution: "fuera",
        desc: ""
    }, {
        id: 575,
        solution: "lat\xedn",
        desc: ""
    }, {
        id: 576,
        solution: "cofre",
        desc: ""
    }, {
        id: 577,
        solution: "talar",
        desc: ""
    }, {
        id: 578,
        solution: "tilde",
        desc: ""
    }, {
        id: 579,
        solution: "canto",
        desc: ""
    }, {
        id: 580,
        solution: "hueco",
        desc: ""
    }, {
        id: 581,
        solution: "rezar",
        desc: ""
    }, {
        id: 582,
        solution: "calle",
        desc: ""
    }, {
        id: 583,
        solution: "pluma",
        desc: ""
    }, {
        id: 584,
        solution: "orden",
        desc: ""
    }, {
        id: 585,
        solution: "vieja",
        desc: ""
    }, {
        id: 586,
        solution: "humor",
        desc: ""
    }, {
        id: 587,
        solution: "fusil",
        desc: ""
    }, {
        id: 588,
        solution: "f\xf3sil",
        desc: ""
    }, {
        id: 589,
        solution: "usual",
        desc: ""
    }, {
        id: 590,
        solution: "favor",
        desc: ""
    }, {
        id: 591,
        solution: "enero",
        desc: ""
    }, {
        id: 592,
        solution: "leche",
        desc: ""
    }, {
        id: 593,
        solution: "calza",
        desc: ""
    }, {
        id: 594,
        solution: "fruta",
        desc: ""
    }, {
        id: 595,
        solution: "comer",
        desc: ""
    }, {
        id: 596,
        solution: "p\xedxel",
        desc: ""
    }, {
        id: 597,
        solution: "usted",
        desc: ""
    }, {
        id: 598,
        solution: "rango",
        desc: ""
    }, {
        id: 599,
        solution: "pitar",
        desc: ""
    }, {
        id: 600,
        solution: "bomba",
        desc: ""
    }, {
        id: 601,
        solution: "bamba",
        desc: ""
    }, {
        id: 602,
        solution: "manco",
        desc: ""
    }, {
        id: 603,
        solution: "robar",
        desc: ""
    }, {
        id: 604,
        solution: "punto",
        desc: ""
    }, {
        id: 605,
        solution: "preso",
        desc: ""
    }, {
        id: 606,
        solution: "poder",
        desc: ""
    }, {
        id: 607,
        solution: "alero",
        desc: ""
    }, {
        id: 608,
        solution: "gotea",
        desc: ""
    }, {
        id: 609,
        solution: "chica",
        desc: ""
    }, {
        id: 610,
        solution: "rabia",
        desc: ""
    }, {
        id: 611,
        solution: "nunca",
        desc: ""
    }, {
        id: 612,
        solution: "dulce",
        desc: ""
    }, {
        id: 613,
        solution: "tribu",
        desc: ""
    }, {
        id: 614,
        solution: "forma",
        desc: ""
    }, {
        id: 615,
        solution: "agudo",
        desc: ""
    }, {
        id: 616,
        solution: "rollo",
        desc: ""
    }, {
        id: 617,
        solution: "rugby",
        desc: ""
    }, {
        id: 618,
        solution: "jab\xf3n",
        desc: ""
    }, {
        id: 619,
        solution: "torta",
        desc: ""
    }, {
        id: 620,
        solution: "hiato",
        desc: ""
    }, {
        id: 621,
        solution: "diodo",
        desc: ""
    }, {
        id: 622,
        solution: "obvia",
        desc: ""
    }, {
        id: 623,
        solution: "riego",
        desc: ""
    }, {
        id: 624,
        solution: "temor",
        desc: ""
    }, {
        id: 625,
        solution: "trozo",
        desc: ""
    }, {
        id: 626,
        solution: "lunar",
        desc: ""
    }, {
        id: 627,
        solution: "motor",
        desc: ""
    }, {
        id: 628,
        solution: "cable",
        desc: ""
    }, {
        id: 629,
        solution: "cagar",
        desc: ""
    }, {
        id: 630,
        solution: "pase\xf3",
        desc: ""
    }, {
        id: 631,
        solution: "banal",
        desc: ""
    }, {
        id: 632,
        solution: "union",
        desc: ""
    }, {
        id: 633,
        solution: "media",
        desc: ""
    }, {
        id: 634,
        solution: "mamut",
        desc: ""
    }, {
        id: 635,
        solution: "tedio",
        desc: ""
    }, {
        id: 636,
        solution: "labio",
        desc: ""
    }, {
        id: 637,
        solution: "bombo",
        desc: ""
    }, {
        id: 638,
        solution: "rasgo",
        desc: ""
    }, {
        id: 639,
        solution: "l\xedder",
        desc: ""
    }, {
        id: 640,
        solution: "reloj",
        desc: ""
    }, {
        id: 641,
        solution: "raz\xf3n",
        desc: ""
    }, {
        id: 642,
        solution: "torre",
        desc: ""
    }, {
        id: 643,
        solution: "jarra",
        desc: ""
    }, {
        id: 644,
        solution: "laica",
        desc: ""
    }, {
        id: 645,
        solution: "ocaso",
        desc: ""
    }, {
        id: 646,
        solution: "amigo",
        desc: ""
    }, {
        id: 647,
        solution: "d\xe9bil",
        desc: ""
    }, {
        id: 648,
        solution: "sabor",
        desc: ""
    }, {
        id: 649,
        solution: "menor",
        desc: ""
    }, {
        id: 650,
        solution: "indio",
        desc: ""
    }, {
        id: 651,
        solution: "dolor",
        desc: ""
    }, {
        id: 652,
        solution: "honra",
        desc: ""
    }, {
        id: 653,
        solution: "obesa",
        desc: ""
    }, {
        id: 654,
        solution: "techo",
        desc: ""
    }, {
        id: 655,
        solution: "ajeno",
        desc: ""
    }, {
        id: 656,
        solution: "tinte",
        desc: ""
    }, {
        id: 657,
        solution: "l\xe9mur",
        desc: ""
    }, {
        id: 658,
        solution: "plana",
        desc: ""
    }, {
        id: 659,
        solution: "caigo",
        desc: ""
    }, {
        id: 660,
        solution: "\xe1nimo",
        desc: ""
    }, {
        id: 661,
        solution: "quema",
        desc: ""
    }, {
        id: 662,
        solution: "bat\xf3n",
        desc: ""
    }, {
        id: 663,
        solution: "f\xe9mur",
        desc: ""
    }, {
        id: 664,
        solution: "bolso",
        desc: ""
    }, {
        id: 665,
        solution: "rodar",
        desc: ""
    }, {
        id: 666,
        solution: "cabal",
        desc: ""
    }, {
        id: 667,
        solution: "ata\xfad",
        desc: ""
    }, {
        id: 668,
        solution: "agrio",
        desc: ""
    }, {
        id: 669,
        solution: "atril",
        desc: ""
    }, {
        id: 670,
        solution: "pelea",
        desc: ""
    }, {
        id: 671,
        solution: "donar",
        desc: ""
    }, {
        id: 672,
        solution: "feroz",
        desc: ""
    }, {
        id: 673,
        solution: "linda",
        desc: ""
    }, {
        id: 674,
        solution: "d\xe1til",
        desc: ""
    }, {
        id: 675,
        solution: "farol",
        desc: ""
    }, {
        id: 676,
        solution: "norte",
        desc: ""
    }, {
        id: 677,
        solution: "rasta",
        desc: ""
    }, {
        id: 678,
        solution: "da\xf1ar",
        desc: ""
    }, {
        id: 679,
        solution: "mot\xedn",
        desc: ""
    }, {
        id: 680,
        solution: "negar",
        desc: ""
    }, {
        id: 681,
        solution: "gorra",
        desc: ""
    }, {
        id: 682,
        solution: "mafia",
        desc: ""
    }, {
        id: 683,
        solution: "letal",
        desc: ""
    }, {
        id: 684,
        solution: "lepra",
        desc: ""
    }, {
        id: 685,
        solution: "\xe1rabe",
        desc: ""
    }, {
        id: 686,
        solution: "lat\xf3n",
        desc: ""
    }, {
        id: 687,
        solution: "angel",
        desc: ""
    }, {
        id: 688,
        solution: "p\xe1del",
        desc: ""
    }, {
        id: 689,
        solution: "pauta",
        desc: ""
    }, {
        id: 690,
        solution: "legua",
        desc: ""
    }, {
        id: 691,
        solution: "freno",
        desc: ""
    }, {
        id: 692,
        solution: "logro",
        desc: ""
    }, {
        id: 693,
        solution: "goteo",
        desc: ""
    }, {
        id: 694,
        solution: "rigor",
        desc: ""
    }, {
        id: 695,
        solution: "pizca",
        desc: ""
    }, {
        id: 696,
        solution: "magma",
        desc: ""
    }, {
        id: 697,
        solution: "\xf3valo",
        desc: ""
    }, {
        id: 698,
        solution: "virgo",
        desc: ""
    }, {
        id: 699,
        solution: "cursi",
        desc: ""
    }, {
        id: 700,
        solution: "batir",
        desc: ""
    }, {
        id: 701,
        solution: "momia",
        desc: ""
    }, {
        id: 702,
        solution: "aleta",
        desc: ""
    }, {
        id: 703,
        solution: "plaga",
        desc: ""
    }, {
        id: 704,
        solution: "apa\xf1a",
        desc: ""
    }, {
        id: 705,
        solution: "llen\xf3",
        desc: ""
    }, {
        id: 706,
        solution: "vigor",
        desc: ""
    }, {
        id: 707,
        solution: "adobo",
        desc: ""
    }, {
        id: 708,
        solution: "junta",
        desc: ""
    }, {
        id: 709,
        solution: "pagar",
        desc: ""
    }, {
        id: 710,
        solution: "ajena",
        desc: ""
    }, {
        id: 711,
        solution: "rodeo",
        desc: ""
    }, {
        id: 712,
        solution: "\xe1cida",
        desc: ""
    }, {
        id: 713,
        solution: "plena",
        desc: ""
    }, {
        id: 714,
        solution: "palco",
        desc: ""
    }, {
        id: 715,
        solution: "asado",
        desc: ""
    }, {
        id: 716,
        solution: "ayuda",
        desc: ""
    }, {
        id: 717,
        solution: "magna",
        desc: ""
    }, {
        id: 718,
        solution: "vibra",
        desc: ""
    }, {
        id: 719,
        solution: "citar",
        desc: ""
    }, {
        id: 720,
        solution: "pulso",
        desc: ""
    }, {
        id: 721,
        solution: "mayor",
        desc: ""
    }, {
        id: 722,
        solution: "termo",
        desc: ""
    }, {
        id: 723,
        solution: "mes\xf3n",
        desc: ""
    }, {
        id: 724,
        solution: "fondo",
        desc: ""
    }, {
        id: 725,
        solution: "tesis",
        desc: ""
    }, {
        id: 726,
        solution: "mueca",
        desc: ""
    }, {
        id: 727,
        solution: "calca",
        desc: ""
    }, {
        id: 728,
        solution: "solar",
        desc: ""
    }, {
        id: 729,
        solution: "prado",
        desc: ""
    }, {
        id: 730,
        solution: "pista",
        desc: ""
    }, {
        id: 731,
        solution: "sudor",
        desc: ""
    }, {
        id: 732,
        solution: "praga",
        desc: ""
    }, {
        id: 733,
        solution: "polen",
        desc: ""
    }, {
        id: 734,
        solution: "aroma",
        desc: ""
    }, {
        id: 735,
        solution: "nuera",
        desc: ""
    }, {
        id: 736,
        solution: "plata",
        desc: ""
    }, {
        id: 737,
        solution: "orina",
        desc: ""
    }, {
        id: 738,
        solution: "libre",
        desc: ""
    }, {
        id: 739,
        solution: "h\xe1bil",
        desc: ""
    }, {
        id: 740,
        solution: "barba",
        desc: ""
    }, {
        id: 741,
        solution: "f\xe9nix",
        desc: ""
    }, {
        id: 742,
        solution: "fiera",
        desc: ""
    }, {
        id: 743,
        solution: "hiena",
        desc: ""
    }, {
        id: 744,
        solution: "cloro",
        desc: ""
    }, {
        id: 745,
        solution: "legal",
        desc: ""
    }, {
        id: 746,
        solution: "jaque",
        desc: ""
    }, {
        id: 747,
        solution: "ozono",
        desc: ""
    }, {
        id: 748,
        solution: "caspa",
        desc: ""
    }, {
        id: 749,
        solution: "brazo",
        desc: ""
    }, {
        id: 750,
        solution: "act\xfaa",
        desc: ""
    }, {
        id: 751,
        solution: "azada",
        desc: ""
    }, {
        id: 752,
        solution: "cup\xf3n",
        desc: ""
    }, {
        id: 753,
        solution: "sedar",
        desc: ""
    }, {
        id: 754,
        solution: "queja",
        desc: ""
    }, {
        id: 755,
        solution: "peaje",
        desc: ""
    }, {
        id: 756,
        solution: "manta",
        desc: ""
    }, {
        id: 757,
        solution: "alg\xfan",
        desc: ""
    }, {
        id: 758,
        solution: "poema",
        desc: ""
    }, {
        id: 759,
        solution: "bruto",
        desc: ""
    }, {
        id: 760,
        solution: "lucha",
        desc: ""
    }, {
        id: 761,
        solution: "pinza",
        desc: ""
    }, {
        id: 762,
        solution: "ruido",
        desc: ""
    }, {
        id: 763,
        solution: "barca",
        desc: ""
    }, {
        id: 764,
        solution: "joder",
        desc: ""
    }, {
        id: 765,
        solution: "litro",
        desc: ""
    }, {
        id: 766,
        solution: "lento",
        desc: ""
    }, {
        id: 767,
        solution: "bello",
        desc: ""
    }, {
        id: 768,
        solution: "capaz",
        desc: ""
    }, {
        id: 769,
        solution: "floja",
        desc: ""
    }, {
        id: 770,
        solution: "pasta",
        desc: ""
    }, {
        id: 771,
        solution: "encia",
        desc: ""
    }, {
        id: 772,
        solution: "clase",
        desc: ""
    }, {
        id: 773,
        solution: "ciega",
        desc: ""
    }, {
        id: 774,
        solution: "congo",
        desc: ""
    }, {
        id: 775,
        solution: "pez\xf3n",
        desc: ""
    }, {
        id: 776,
        solution: "motel",
        desc: ""
    }, {
        id: 777,
        solution: "ara\xf1a",
        desc: ""
    }, {
        id: 778,
        solution: "gorda",
        desc: ""
    }, {
        id: 779,
        solution: "enana",
        desc: ""
    }, {
        id: 780,
        solution: "venda",
        desc: ""
    }, {
        id: 781,
        solution: "estoy",
        desc: ""
    }, {
        id: 782,
        solution: "oigan",
        desc: ""
    }, {
        id: 783,
        solution: "chivo",
        desc: ""
    }, {
        id: 784,
        solution: "aliar",
        desc: ""
    }, {
        id: 785,
        solution: "tinta",
        desc: ""
    }, {
        id: 786,
        solution: "pecho",
        desc: ""
    }, {
        id: 787,
        solution: "ocupa",
        desc: ""
    }, {
        id: 788,
        solution: "mambo",
        desc: ""
    }, {
        id: 789,
        solution: "barco",
        desc: ""
    }, {
        id: 790,
        solution: "casco",
        desc: ""
    }, {
        id: 791,
        solution: "kenia",
        desc: ""
    }, {
        id: 792,
        solution: "creer",
        desc: ""
    }, {
        id: 793,
        solution: "plato",
        desc: ""
    }, {
        id: 794,
        solution: "mudar",
        desc: ""
    }, {
        id: 795,
        solution: "apnea",
        desc: ""
    }, {
        id: 796,
        solution: "manso",
        desc: ""
    }, {
        id: 797,
        solution: "crudo",
        desc: ""
    }, {
        id: 798,
        solution: "busto",
        desc: ""
    }, {
        id: 799,
        solution: "bromo",
        desc: ""
    }, {
        id: 800,
        solution: "ritmo",
        desc: ""
    }, {
        id: 801,
        solution: "banco",
        desc: ""
    }, {
        id: 802,
        solution: "simio",
        desc: ""
    }, {
        id: 803,
        solution: "deber",
        desc: ""
    }, {
        id: 804,
        solution: "\xe9tica",
        desc: ""
    }, {
        id: 805,
        solution: "viejo",
        desc: ""
    }, {
        id: 806,
        solution: "labor",
        desc: ""
    }, {
        id: 807,
        solution: "tarot",
        desc: ""
    }, {
        id: 808,
        solution: "fauna",
        desc: ""
    }, {
        id: 809,
        solution: "china",
        desc: ""
    }, {
        id: 810,
        solution: "liceo",
        desc: ""
    }, {
        id: 811,
        solution: "sismo",
        desc: ""
    }, {
        id: 812,
        solution: "d\xf3cil",
        desc: ""
    }, {
        id: 813,
        solution: "acero",
        desc: ""
    }, {
        id: 814,
        solution: "horda",
        desc: ""
    }, {
        id: 815,
        solution: "salud",
        desc: ""
    }, {
        id: 816,
        solution: "l\xednea",
        desc: ""
    }, {
        id: 817,
        solution: "carpa",
        desc: ""
    }, {
        id: 818,
        solution: "celta",
        desc: ""
    }, {
        id: 819,
        solution: "sushi",
        desc: ""
    }, {
        id: 820,
        solution: "tonta",
        desc: ""
    }, {
        id: 821,
        solution: "parto",
        desc: ""
    }, {
        id: 822,
        solution: "virar",
        desc: ""
    }, {
        id: 823,
        solution: "pecar",
        desc: ""
    }, {
        id: 824,
        solution: "falta",
        desc: ""
    }, {
        id: 825,
        solution: "narco",
        desc: ""
    }, {
        id: 826,
        solution: "guapa",
        desc: ""
    }, {
        id: 827,
        solution: "miedo",
        desc: ""
    }, {
        id: 828,
        solution: "fugar",
        desc: ""
    }, {
        id: 829,
        solution: "medio",
        desc: ""
    }, {
        id: 830,
        solution: "tenor",
        desc: ""
    }, {
        id: 831,
        solution: "regar",
        desc: ""
    }, {
        id: 832,
        solution: "choca",
        desc: ""
    }, {
        id: 833,
        solution: "pared",
        desc: ""
    }, {
        id: 834,
        solution: "arden",
        desc: ""
    }, {
        id: 835,
        solution: "pasar",
        desc: ""
    }, {
        id: 836,
        solution: "genia",
        desc: ""
    }, {
        id: 837,
        solution: "herir",
        desc: ""
    }, {
        id: 838,
        solution: "savia",
        desc: ""
    }, {
        id: 839,
        solution: "posar",
        desc: ""
    }, {
        id: 840,
        solution: "segar",
        desc: ""
    }, {
        id: 841,
        solution: "vapor",
        desc: ""
    }, {
        id: 842,
        solution: "falda",
        desc: ""
    }, {
        id: 843,
        solution: "bel\xe9n",
        desc: ""
    }, {
        id: 844,
        solution: "tramo",
        desc: ""
    }, {
        id: 845,
        solution: "corre",
        desc: ""
    }, {
        id: 846,
        solution: "madre",
        desc: ""
    }, {
        id: 847,
        solution: "zorra",
        desc: ""
    }, {
        id: 848,
        solution: "koala",
        desc: ""
    }, {
        id: 849,
        solution: "cerro",
        desc: ""
    }, {
        id: 850,
        solution: "lecho",
        desc: ""
    }, {
        id: 851,
        solution: "romeo",
        desc: ""
    }, {
        id: 852,
        solution: "morir",
        desc: ""
    }, {
        id: 853,
        solution: "aguja",
        desc: ""
    }, {
        id: 854,
        solution: "viuda",
        desc: ""
    }, {
        id: 855,
        solution: "botar",
        desc: ""
    }, {
        id: 856,
        solution: "rifle",
        desc: ""
    }, {
        id: 857,
        solution: "serie",
        desc: ""
    }, {
        id: 858,
        solution: "canje",
        desc: ""
    }, {
        id: 859,
        solution: "\xe9tico",
        desc: ""
    }, {
        id: 860,
        solution: "bravo",
        desc: ""
    }, {
        id: 861,
        solution: "capto",
        desc: ""
    }, {
        id: 862,
        solution: "\xe9pico",
        desc: ""
    }, {
        id: 863,
        solution: "ameba",
        desc: ""
    }, {
        id: 864,
        solution: "muero",
        desc: ""
    }, {
        id: 865,
        solution: "aforo",
        desc: ""
    }, {
        id: 866,
        solution: "cieno",
        desc: ""
    }, {
        id: 867,
        solution: "doblo",
        desc: ""
    }]